---
- include_vars: "/usr/local/etc/ansible/host_vars/{{ ansible_nodename }}-secrets.yml"
  tags:
    - always

- name: Copy .env file into place
  become: yes
  template:
    src: ".env.j2"
    dest: "{{ django_env_path }}"
  tags:
    - codedeploy

- name: Run collectstatic
  become: yes
  django_manage:
    command: collectstatic
    app_path: "{{ django_root }}"
    virtualenv: "{{ django_virtualenv_path }}"
  tags:
    - codedeploy

- name: Create django media root directory
  become: yes
  file:
    path: "{{ django_media_root }}"
    state: directory
    owner: www
    group: www

- name: Create django media root subdirectories
  become: yes
  file:
    path: "{{ django_media_root }}/{{ item }}"
    state: directory
    owner: www
    group: www
  with_items: "{{ django_media_root_subdirs }}"

- name: Copy djangomanage rc.d script
  become: yes
  template:
    src: djangomanage.j2
    dest: "/usr/local/etc/rc.d/djangomanage"
    owner: root
    group: wheel
    mode: "555"

- name: Configure djangomanage_path
  become: yes
  sysrc:
    name: djangomanage_path
    value: "{{ django_root }}manage.py"

- name: Configure djangomanage_user
  become: yes
  sysrc:
    name: djangomanage_user
    value: "www"

- name: Configure djangomanage_group
  become: yes
  sysrc:
    name: djangomanage_group
    value: "www"

- name: Configure djangomanage_profiles
  become: yes
  sysrc:
    name: djangomanage_profiles
    value: "invoice"

- name: Configure djangomanage_invoice_args
  become: yes
  sysrc:
    name: djangomanage_invoice_args
    value: "invoice-worker"

- name: Configure djangomanage_invoice_logfile
  become: yes
  sysrc:
    name: djangomanage_invoice_logfile
    value: "/var/log/bornhack-invoice-worker.log"

- name: Enable djangomanage
  become: yes
  service:
    name: djangomanage
    enabled: yes

- name: Restart djangomanage workers
  become: yes
  service:
    name: djangomanage
    state: restarted
  tags:
    - codedeploy

