---
- name: "Make sure uwsgi newsyslog config file exists"
  copy:
    owner: "root"
    group: "wheel"
    mode: "755"
    src: "uwsgi-newsyslog.conf"
    dest: "/usr/local/etc/newsyslog.conf.d/uwsgi"

