---
- name: "restart daphne using supervisorctl"
  command: "/usr/local/bin/supervisorctl restart daphne"

- name: "restart supervisord_extra_programs"
  command: "/usr/local/bin/supervisorctl restart {{ item.name }}"
  with_items: "{{ supervisord_extra_programs | default({}) }}"

