---
- name: "Install pip"
  pkgng:
    name: "py37-pip"
    state: "present"

- name: "Install setuptools"
  pkgng:
    name: "py37-setuptools"
    state: "present"

- name: "Check if we have an existing virtualenv for Certgrinder"
  stat:
    path: "{{ certgrinder_home }}/virtualenv/"
  register: certgrinder_virtualenv
  changed_when: False

- name: "Check Python version of venv for Certgrinder"
  command: "{{ certgrinder_home }}/virtualenv/bin/python -V"
  register: python_version
  changed_when: False
  when: certgrinder_virtualenv.stat.exists

- name: "Remove py2.x venv if we have one"
  file:
    state: "absent"
    path: "{{ certgrinder_home }}/virtualenv"
  when:
    - certgrinder_virtualenv.stat.exists
    - python_version.stderr[0:8] == "Python 2"

- name: "Install virtualenv"
  pkgng:
    name: "py37-virtualenv"
    state: "present"

- name: "Install Rust (build dep for cryptography)"
  pkgng:
    name: "rust"
    state: "present"
  register: rustresult

- name: "Create new virtualenv and install cryptography. Use CFLAGS and LDFLAGS env vars to force pip to use /usr/local/ ports OpenSSL include"
  pip:
    virtualenv_python: "python"
    name: "cryptography"
    virtualenv: "{{ certgrinder_home }}/virtualenv"
    extra_args: '--global-option=build_ext'
  environment:
    CFLAGS: "-I/usr/local/include"
    LDFLAGS: "-L/usr/local/include"

- name: "Remove Rust build dep if we installed it"
  pkgng:
    name: "rust"
    state: "absent"
  when:
    - rustresult.changed

- name: "Upgrade pip to latest version to avoid problems when installing cffi"
  pip:
    name: "pip"
    state: "latest"
    virtualenv: "{{ certgrinder_home }}/virtualenv"

- name: "Install or upgrade certgrinder in the virtualenv"
  pip:
    name: "certgrinder"
    state: "latest"
    virtualenv: "{{ certgrinder_home }}/virtualenv"

- name: "Create certificates directory"
  file:
    dest: "{{ certgrinder_home }}/certificates"
    state: "directory"
    mode: "0750"
    owner: "{{ certgrinder_user }}"

- name: "Create certgrinder.conf config file"
  template:
    src: "certgrinder.conf.j2"
    dest: "{{ certgrinder_home }}/certgrinder.conf"
    owner: "{{ certgrinder_user }}"
    mode: "0644"

- name: "Create hooks.d directory"
  file:
    dest: "{{ certgrinder_home }}/hooks.d"
    state: "directory"
    mode: "0755"
    owner: "{{ certgrinder_user }}"
