---
- name: "Make sure certgrinder newsyslog config file exists"
  copy:
    owner: "root"
    group: "wheel"
    mode: "755"
    src: "certgrinder-newsyslog.conf"
    dest: "/usr/local/etc/newsyslog.conf.d/certgrinder"

