---
- name: "Get source code for postgres_exporter with git so we know when it changed, not used for the build"
  git:
    repo: "https://github.com/wrouesnel/postgres_exporter"
    dest: "/root/postgres_exporter"
    force: yes
    version: "{{ postgres_exporter_version }}"
  register: gitresult

- name: "Install Go to build postgres_exporter"
  pkgng:
    name: "go"
    state: "present"
  register: goresult
  when: gitresult.changed
 
- name: "Install gmake to build postgres_exporter"
  pkgng:
    name: "gmake"
    state: "present"
  register: gmakeresult
  when: gitresult.changed

- name: "Build postgres_exporter"
  command: "gmake build"
  args:
    chdir: "/root/postgres_exporter"
  when: gitresult.changed

- name: "Remove Go build dep if we installed it"
  pkgng:
    name: "go"
    state: "absent"
  when:
    - gitresult.changed
    - goresult.changed

- name: "Remove gmake build dep if we installed it"
  pkgng:
    name: "gmake"
    state: "absent"
  when:
    - gitresult.changed
    - gmakeresult.changed

- name: "Copy postgres_exporter binary to /usr/local/bin"
  copy:
   src: "/root/postgres_exporter/postgres_exporter"
   dest: "/usr/local/bin/postgres_exporter"
   remote_src: True
   mode: 0755
  when:
    - gitresult.changed
  notify:
    - "restart postgres_exporter"

- name: "Copy postgres_exporter queries.yml to /usr/local/etc"
  copy:
   src: "/root/postgres_exporter/queries.yaml"
   dest: "/usr/local/etc/postgres_exporter_queries.yml"
   remote_src: yes
  when:
    - gitresult.changed
  notify:
    - "restart postgres_exporter"

- name: "Add any custom queries to postgres_exporter_queries.yml"
  blockinfile:
    dest: "/usr/local/etc/postgres_exporter_queries.yml"
    marker: "# custom postgres_exporter queries added by ansible below here - not part of the default distributed queries.yaml"
    content: "{{ postgresql_exporter_extra_queries | to_nice_yaml(indent=2) | indent(2,False) }}"
  when: postgresql_exporter_extra_queries is defined
  notify:
    - "restart postgres_exporter"

- name: "Create supervisord.d config file to run postgres_exporter"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "postgres_exporter"
    supervisord_programs:
      - name: "postgres_exporter"
        comment: "run postgres_exporter"
        #command: "/usr/local/bin/postgres_exporter --auto-discover-databases --extend.query-path=/usr/local/etc/postgres_exporter_queries.yml"
        command: "/usr/local/bin/postgres_exporter --auto-discover-databases"
        user: "{{ postgresql_user }}"
        environment:
          DATA_SOURCE_NAME: "postgresql://{{ ansible_nodename }}:5432/postgres?sslmode=disable"
    supervisord_extra_programs: []

- name: "Create exporter_exporter.d config file for postgres_exporter"
  include_role:
    name: "freebsd_base"
    tasks_from: "exporter_exporter.d"
  vars:
    expexp_filename: "postgres_exporter.yml"
    expexp_program:
      method: "http"
      http:
        port: 9187
