---
- name: "Add tykbackup user"
  user:
    name: "{{ tykbackup_user }}"
    comment: "tykbackup user"

- name: "Add ssh authorized_keys for all tykbackup clients"
  authorized_key:
    user: "{{ tykbackup_user }}"
    key: "{{ item.authkey }}"
    key_options: 'from="{{ item.fromip }}",restrict,command="/usr/local/bin/zfscmd.sh" {{ item.comment }}'
  with_items: "{{ tykbackup_authorized_keys | default([]) }}"

