---
- name: Install thttpd
  become: yes
  pkgng:
    name: thttpd
    state: present

- name: Enable thttpd
  become: yes
  service:
    name: thttpd
    enabled: yes

- name: Copy thttpd config
  become: yes
  template:
    src: thttpd.conf.j2
    dest: /usr/local/etc/thttpd.conf

- name: Start thttpd (if not running)
  become: yes
  service:
    name: thttpd
    state: started

