---
- name: "Install node_exporter"
  pkgng:
    name: "node_exporter"
    state: "present"

- name: "Create textfile collector directory"
  file:
    path: "{{ node_exporter_textfile_path }}"
    state: "directory"

- name: "Create supervisord.d config file to run node_exporter"
  include_role:
    name: "supervisord_server"
    tasks_from: "supervisord.d"
  vars:
    supervisord_filename: "node_exporter"
    supervisord_programs:
      - name: "node_exporter"
        comment: "run node_exporter"
        command: "/usr/local/bin/node_exporter --web.listen-address={{ node_exporter_listen_address }} --collector.textfile.directory={{ node_exporter_textfile_path }} "
        user: "{{ prometheus_exporter_user }}"
    supervisord_extra_programs: []

